DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS token;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  real_name TEXT NOT NULL,
  password TEXT NOT NULL,
  address TEXT DEFAULT NULL,
  city TEXT DEFAULT NULL,
  country TEXT DEFAULT NULL,
  is_admin INTEGER DEFAULT 0
);

CREATE TABLE token (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  jti TEXT UNIQUE NOT NULL,
  expired INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
