version: "3.8"

services:
  auth_service:
    build: ./auth_service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=supersecret
      - JWT_SECRET_KEY=superjwt
      - DATABASE=instance/armma.sqlite
      - PYTHONPATH=/app
    volumes:
      - ./auth_service/instance:/app/instance
    networks:
      - kong-net

  accounts_service:
    build: ./accounts_service
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=supersecret
      - JWT_SECRET_KEY=superjwt
      - DATABASE=instance/armma.sqlite
      - PYTHONPATH=/app
    volumes:
      - ./auth_service/instance:/app/instance
    networks:
      - kong-net

  transactions_service:
    build: ./transactions_service
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=supersecret
      - JWT_SECRET_KEY=superjwt
      - DATABASE=instance/armma.sqlite
      - PYTHONPATH=/app
    volumes:
      - ./auth_service/instance:/app/instance
    networks:
      - kong-net

  kong:
    build: ./api_gateway
    ports:
      - "8000:8000"  # proxy (public routes)
      - "8001:8001"  # admin API
    depends_on:
      - auth_service
      - accounts_service
      - transactions_service
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
